### ISSUE TITLE
App icon doesn't work?

### ISSUE THREAD

**Issue by Jap2-0** [tckmn/semitone#31] opened 2024-03-12 02:11 UTC
First of all - this is a super useful app, it's simple and it works and it doesn't have ads or waste space and that's wonderful.  Thanks much.

Second: I updated to version 1.3.1 (from the play store) today, and now when clicking the app icon, I just get a toast that says "App isn't installed."  I've tried removing from and re-adding to the home screen, as well as uninstalling and reinstalling, with no success.  If I long-press on the icon and click "app info", a description page does come up, and from the the "open" button launches the app.

I'm not sure if this is an app issue or an Android issue, but it isn't something I've run into before with anything else.  I'm running a Pixel 4a on Android 13; let me know if there's anything else of use I can provide.

**Comment by tckmn** [comment] 2024-03-12 06:36
Thanks very much for the report (and the kind words)! It seems like the cause was a silly typo, and this should be fixed in 1.3.2 once it gets pushed to the Play Store.

**Closed as completed by tckmn** 2024-03-12 06:36 UTC

**Comment by Jap2-0** [comment] 2024-03-13 01:06
Thanks for the quick fix!  Everything seems to be working well once again.
